# Use an official Python runtime as a parent image
FROM python:3.9-slim

RUN apt-get update && apt-get upgrade -y && apt-get install gcc --yes

RUN apt-get update && apt-get install -y \
        libportaudio2 libportaudiocpp0 portaudio19-dev tk \
        python3-dev \
        build-essential \
        && rm -rf /var/lib/apt/lists/*

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run app.py when the container launches
CMD ["python", "app-docker.py"]
